server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: <loki_url>/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      host: <host_name>
      __path__: /var/log/*log
- job_name: journal
  journal:
    json: false
    max_age: 8h
    path: /var/log/journal
    labels:
      job: systemd-journal
      host: <host_name>
  relabel_configs:
    - source_labels: ['__journal__systemd_unit']
      target_label: 'unit'